name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Generate your content
        run: echo "Optional placeholder. Put your project's static website generator command here."

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          source-directory: ./build/web
          destination_dir: .